mariadb -uroot -p"${MYSQL_ROOT_PASSWORD}" -e \
"STOP SLAVE;
CHANGE MASTER TO
  MASTER_HOST='replica_auto_ssh',
  MASTER_USER='${REPLICATION_USER}',
  MASTER_PASSWORD='${REPLICATION_PASSWORD}',
  MASTER_PORT=${REPLICA_LOCAL_PORT},
  MASTER_CONNECT_RETRY=10;
FLUSH PRIVILEGES;
DROP USER IF EXISTS '${MYSQL_USER}';
FLUSH PRIVILEGES;
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT SELECT ON dsg.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
FLUSH PRIVILEGES;
START SLAVE;"
