#!/bin/bash

set -gx JAVA_HOME /opt/homebrew/opt/java/
rm -r deploy/*
rm -r deployClasses/*
rsync -vurtd --exclude-from exclude_compile.txt --stats --progress dsg_src/java/ deploy/
clear; printf '\e[3J';
ant
