#!/bin/bash

set -gx JAVA_HOME /usr/local/opt/openjdk@11/

rm -r deploy/*
rsync -v -u -r -t --exclude test --exclude opengl --exclude swing --exclude demo --stats --progress dsg_src/java/ deploy/
ant

