#!/bin/bash

sh justCompile
rsync -vurt --checksum --stats --exclude .DS_Store --progress "deployClasses/" -e ssh "rainwolf@pente.org:~/tomcat/WEB-INF/classes/"
rsync -vurt --checksum --stats --exclude .DS_Store --progress "/Users/waliedothman/mariposa/coding/pente.org/dsg_src/httpdocs/gameServer/" -e ssh "rainwolf@pente.org:~/tomcat/gameServer/"
ssh rainwolf@pente.org chown -R rainwolf:tomcat8 tomcat/
ssh -t rainwolf@pente.org sudo ./restartTomcat.sh
