create table player (pid bigint generated by default as identity primary key, name varchar(100) not null, site_id smallint not null, name_lower varchar(100));
create table game_db (dbid smallint generated by default as identity primary key, name varchar(100) not null, version varchar(20));
create table game_site (sid smallint generated by default as identity primary key, name varchar(100) not null, short_name varchar(10), URL varchar(100));
create table game_event (eid int generated by default as identity primary key, name varchar(100) not null, site_id smallint not null, mailing_list varchar(30), game smallint not null);
create table pente_game (gid bigint not null, site_id smallint not null, event_id int not null, round varchar(100), section varchar(100), play_date timestamp not null, timer char(1) not null, rated char(1) not null, initial_time smallint, incremental_time smallint, player1_pid bigint not null, player2_pid bigint not null, player1_rating smallint, player2_rating smallint, winner smallint, player1_type char(1) not null, player2_type char(1) not null, game smallint not null,swapped char(1) not null,private char(1) not null); 
create table pente_move (gid bigint not null, move_num smallint not null, next_move smallint not null, hash_key bigint not null, rotation smallint not null, game smallint not null, winner smallint not null, play_date timestamp not null);

-- import data from pente.org [if not made ddl changes already]

alter table game_site alter column sid restart with 5;
alter table game_event alter column eid restart with 10000;
alter table player alter column pid restart with 60000000000000;

alter table game_db alter column dbid restart with 10;

-- set table lock type

create table plunk_prop (name varchar(64) primary key, value blob);

create table plunk_tree(
tree_id bigint primary key generated always as identity,
name varchar(128) not null,
version varchar(64) not null,
creator varchar(64) not null,
can_edit_props char(1) not null,
last_update_dt timestamp not null,
creation_dt timestamp not null
);

create table plunk_node(
tree_id bigint not null,
hash_key bigint not null,
parent_hash_key bigint not null,
rotation smallint not null,
move smallint not null,
depth smallint not null,
type smallint not null,
name varchar(32),
comments varchar(1024)
);
alter table plunk_node add primary key(tree_id, hash_key, depth);
//depth not really part of primary key but will help to be indexed for retrieval?

alter table pente_move add dbid smallint not null default 1;
alter table pente_game add dbid smallint not null default 1;

create index nm on player (name_lower, pid);
//create index nm on player (pid, name_lower);

alter table pente_game add primary key(gid, dbid);
create index p1 on pente_game (dbid, game, player1_pid);
create index p2 on pente_game (dbid, game, player2_pid);
create index venue on pente_game (dbid, game, site_id, event_id, round, section);

alter table pente_move add primary key(gid, move_num, dbid);
alter table pente_move add comments varchar(1024);
alter table pente_move add name varchar(32);
alter table pente_move add type smallint;

-- this is for getting games
create index gid on pente_move (hash_key, move_num, game, dbid, play_date, gid);
-- this is for getting next moves
create index nextm on pente_move (hash_key, move_num, game, dbid, next_move, rotation, winner); 

insert into game_db
values(1, 'Pente Pro', '0.1');


-- insert a sample move database and have it open one first use
-- need a java script to create/populate the database as either part of installation
   or on first run