mariadb -uroot -p"${MYSQL_ROOT_PASSWORD}" -e \
"CHANGE MASTER TO
  MASTER_HOST='replica_auto_ssh',
  MASTER_USER='${REPLICATION_USER}',
  MASTER_PASSWORD='${REPLICATION_PASSWORD}',
  MASTER_PORT=${REPLICA_LOCAL_PORT},
  MASTER_CONNECT_RETRY=10;"