mariadb -uroot -p${MYSQL_ROOT_PASSWORD} -e \
"DROP USER IF EXISTS '${REPLICATION_USER}'@'%';
FLUSH PRIVILEGES;
CREATE USER '${REPLICATION_USER}'@'%' IDENTIFIED BY '${REPLICATION_PASSWORD}';
GRANT REPLICATION SLAVE ON *.* TO '${REPLICATION_USER}'@'%';
FLUSH PRIVILEGES;
DROP USER IF EXISTS '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL ON dsg.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;"
